meta_product_name: "Stroll"
meta_title: "Stroll | Discover what's around you"
meta_description: "Discover what’s around the corner, across the country and everything in-between. Use our free walking routes to find new interesting locations around you."
meta_image: "cover.jpg" # should exist in `app/assets/images/`


